---
development:
  cloud_name: dxgiuxvya
  api_key: '456459468585972'
  api_secret: hvpPDpuDSb0-g3fTNC4YF7TjvEk
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dxgiuxvya
  api_key: '456459468585972'
  api_secret: hvpPDpuDSb0-g3fTNC4YF7TjvEk
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dxgiuxvya
  api_key: '456459468585972'
  api_secret: hvpPDpuDSb0-g3fTNC4YF7TjvEk
  enhance_image_tag: true
  static_image_support: false
